# Generated by Django 5.2.16 on 2026-07-31 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0002_alter_lesson_topic_alter_problem_topic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(help_text="The user's source code submission.")),
                ('language', models.CharField(choices=[('python', 'Python 3'), ('javascript', 'JavaScript'), ('cpp', 'C++'), ('java', 'Java')], default='python', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('ACCEPTED', 'Accepted'), ('WRONG_ANSWER', 'Wrong Answer'), ('TIME_LIMIT_EXCEEDED', 'Time Limit Exceeded'), ('RUNTIME_ERROR', 'Runtime Error'), ('COMPILE_ERROR', 'Compile Error')], default='PENDING', max_length=25)),
                ('passed_test_cases', models.IntegerField(default=0)),
                ('total_test_cases', models.IntegerField(default=0)),
                ('runtime', models.FloatField(blank=True, help_text='Execution time in seconds.', null=True)),
                ('memory', models.IntegerField(blank=True, help_text='Memory usage in KB.', null=True)),
                ('stdout', models.TextField(blank=True, help_text="Standard output from the user's program execution.", null=True)),
                ('error_message', models.TextField(blank=True, help_text='Stderr or stack trace if a runtime/compile error occurs.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='curriculum.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.JSONField(help_text='The input parameters (e.g., arrays, strings, integers) as JSON objects.')),
                ('expected_output', models.JSONField(help_text='The expected return value or output as a JSON object.')),
                ('is_sample', models.BooleanField(default=False, help_text='If True, this is visible to the user as an example.')),
                ('order', models.PositiveIntegerField(default=1, help_text='The execution sequence for the test cases.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='curriculum.problem')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
