# Generated by Django 5.2.16 on 2026-07-31 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_alter_lesson_topic_alter_problem_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='function_name',
            field=models.CharField(default='solution', help_text="The name of the function the user must define (e.g., 'two_sum').", max_length=100),
        ),
    ]
