# Generated by Django 5.2.16 on 2026-07-31 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_problem_function_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='parameter_names',
            field=models.JSONField(blank=True, default=list, help_text='List of parameter names for the function signature, e.g. ["nums", "target"]. These must match the keys in each TestCase\'s input_data JSON.'),
        ),
    ]
