# Generated by Django 5.2.16 on 2026-08-01 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0004_problem_parameter_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('order', models.PositiveIntegerField(default=1, help_text='Display order on the dashboard.')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='topic',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='curriculum.category'),
        ),
    ]
