# Generated by Django 5.2.16 on 2026-09-07 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0006_problem_parameter_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='parameter_types',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='problem',
            name='return_type',
            field=models.CharField(default='int', max_length=20),
        ),
    ]
